### ISSUE TITLE
Permissions not working correctly

### ISSUE THREAD

**Issue by mhdask** [netbox-community/netbox-floorplan-plugin#11]
Currently the permissions are not working correctly, and only superusers can see the tabs.
The "upstream" version had this fixed 4 months ago: 
https://github.com/tbotnz/netbox_floorplan/commit/163d792bc388af245c5e50abe00d7b49a9579fda and https://github.com/tbotnz/netbox_floorplan/commit/6feea183c660b3e7c418feb31d9b2cdd44ae9614.

Could the same fixes be applied here?

**Comment by Luth1ng** [comment]
Hello, facing the same issue here, can you apply the fix on this branch ?

**Comment by opensourceXnetbox** [comment]
> Hello, facing the same issue here, can you apply the fix on this branch ?

Hey, having the same problem. Thats a neccessary function for this plugin!

**Comment by jeffgdotorg** [comment]
@mhdask thanks for raising this. Working on getting your PR merged between meetings.

**Comment by jeffgdotorg** [comment]
Reopening so that @mhdask can create a follow-on PR to address a typo.
