### ISSUE TITLE
Change background on floorplan

### ISSUE THREAD

**Issue by deku-m** [netbox-community/netbox-floorplan-plugin#2]
Would be great to provide a background image upload/add possibility. As for example a sitemap/drawing of the location/site.
So that we can place the created dimension on it and also place the rack and match it on the drawing.

As example:
![288801728-fcb3eb02-b717-4851-af99-2a7e2a6316ff](https://github.com/netbox-community/netbox-floorplan-plugin/assets/37069737/dbae75af-fe03-4cb7-bab2-a80863e42df3)

**Comment by cruse1977** [comment]
This is a significant level of JS work and would need a JS developer.
