### ISSUE TITLE
 Current supported Netbox 4.0 Version?

### ISSUE THREAD

**Issue by nsauter** [netbox-community/netbox-floorplan-plugin#24]
Hello!

I noticed thta some users are trying to install this plugin in their Netbox v4 environment. Could you please update the compatibility?

Thanks!

**Comment by natm** [comment]
https://linear.app/netboxlabs/issue/ENG-2991/

**Comment by darkcloud784** [comment]
> https://linear.app/netboxlabs/issue/ENG-2991/

Ah yes, share a link to something no one has access to. Thats the best way to answer.

**Comment by cruse1977** [comment]
> > https://linear.app/netboxlabs/issue/ENG-2991/
> 
> Ah yes, share a link to something no one has access to. Thats the best way to answer.

 This is a quick ref which means it's being worked on. We'll communicate this differently next time.
