### ISSUE TITLE
Un-racked devices not listed when editing

### ISSUE THREAD

**Issue by matejv** [netbox-community/netbox-floorplan-plugin#35]
When editing floorplan for location when I click on Un-racked devices there are no devices listed even when I have some devices under Location but not in Rack.

Looking through the code, I see there are two ajax calls [here](https://github.com/netbox-community/netbox-floorplan-plugin/blob/0c4007f593ae668379b8555ff6a8e8031306c718/netbox_floorplan/static/netbox_floorplan/floorplan/edit.js#L25). 

Using browser developer tools I see that the first URL (`/plugins/floorplan/floorplans/racks/?floorplan_id=1`) is called and loaded, but the second (`/plugins/floorplan/floorplans/devices/?floorplan_id=1`) is not called by the browser at all. 

![image](https://github.com/user-attachments/assets/1f79d63b-f584-4160-9eae-1cd428819854)

If I use browser developer tools to set a breakpoint to the first ajax call and then just continue execution (so just a small pause is introduced) it works - both URLs are called and shown correctly. So there might be a race condition of some kind?

Tested on:
- netbox 4.0.7
- netbox-floorplan 0.4.0
- firefox 127 and chromium 126

**Comment by timeu** [comment]
This is related to this issue: https://github.com/bigskysoftware/htmx/issues/2147. 
Solution is to provide the source to the `htmx.ajax` call
