### ISSUE TITLE
Object can´t be deleted or moved

### ISSUE THREAD

**Issue by NotHBlocks** [netbox-community/netbox-floorplan-plugin#40]
We´ve got a bug where some lables are stuck. They can´t be moved or deleted. If I hover over an label with text in it the cursor will transform into the move symbol, but clicking or dragging doesn´t work. The key "DEL" on the keyboard doesn´t work either. Is there a fix for it instead of deleting the whole floorplan?

Thank you in advance.

**Comment by cruse1977** [comment]
Hi, I've not been able to reproduce this sadly so I'm going to close as no idea how to replicate this
