### ISSUE TITLE
Viewing a floorplan logs a change

### ISSUE THREAD

**Issue by st-nip** [netbox-community/netbox-floorplan-plugin#42]
The act of simply viewing a floorplan logs a change.

This fills out the change log entirely unnecessarily with events containing:
```
Difference
No Changes
```

It makes me wonder how it would operate with a user that only has read permissions.

**Comment by uedvt359** [comment]
when viewing a floorplan, it gets automatically modified to update device name and status labels. i've created a patch to only do this when an actual changed occurred: https://github.com/netbox-community/netbox-floorplan-plugin/pull/59
