### ISSUE TITLE
Support for 4.1.0

### ISSUE THREAD

**Issue by bogi788** [netbox-community/netbox-floorplan-plugin#43]
Both Netbox 4.0.11 and 4.1.0 have been released this week. The floorplan raises an ImproperlyConfigured exception on both because the maximum version was set to 4.0.10 in https://github.com/netbox-community/netbox-floorplan-plugin/commit/fadfe4428c95654a665f5123e4575bd9152361f6.

**Comment by FromNetToDev** [comment]
Hello, I got same issue, the problem is that the plugin does not support version 4.1.0 (the maximum supported version is 4.0.10), please consider fixing this

**Comment by uedvt359** [comment]
pinning on the patch-level is wrong IMO. There should not be any breakage on patch releases, so this only causes unnecessary delays until a new floorplan release is cut.

**Comment by darkfritz2** [comment]
we have already version 4.1.1....

**Comment by Zheer09** [comment]
Yes because of this i can not use this plugin it throw that the maximum netbox is 4.0.10 but i have 4.1.0

**Comment by brandan-schmitz** [comment]
Any update on this? is there any other changes that are needed to make the plugin compatible with Netbox 4.1.x aside from just updating the max version in the `setup.py` file?

**Comment by ZachHoiberg** [comment]
In the meantime, you can apply the following to get this running:

1. Install the floorplan plugin as normal
2. Modify the max_version in `/opt/netbox-X.Y.Z/venv/lib/python3.11/site-packages/netbox_floorplan/__init__.py`, replacing X.Y.Z with your version.
3. `cd /opt/netbox`
4. `sudo ./venv/bin/python3 netbox/manage.py makemigrations netbox_floorplan_plugin`
5. `sudo ./venv/bin/python3 netbox/manage.py migrate`
6. `sudo systemctl restart netbox netbox-rq`

**Comment by darkfritz2** [comment]
this is not the "way" but seems to be working...

**Comment by cruse1977** [comment]
Hello, 0.4.1 will support 4.0.11, 0.5.0 will support 4.1 - should be coming next few days

**Comment by uedvt359** [comment]
great to hear, @cruse1977! but please, please, please don't pin the netbox version on the patch level. most of us would rather risk it partially breaking at runtime, rather than refusing to start up at all.

afaik, the netbox team only introduces breaking changes at the minor level (i.e, y in x.y.z), but never the patch level (i.e, z in x.y.z).

**Comment by cruse1977** [comment]
> great to hear, @cruse1977! but please, please, please don't pin the netbox version on the patch level. most of us would rather risk it partially breaking at runtime, rather than refusing to start up at all.
> 
> afaik, the netbox team only introduces breaking changes at the minor level (i.e, y in x.y.z), but never the patch level (i.e, z in x.y.z).

I agree.

**Comment by tfboy** [comment]
> Hello, 0.4.1 will support 4.0.11, 0.5.0 will support 4.1 - should be coming next few days

Hi Chris, any news on a 0.5.0 version supporting NetBox 4.1.x ? I'm really eager to bring this back into my datacenter.
Thanks for this great plugin 🥇

**Comment by dmeshalkin** [comment]
> Hello, 0.4.1 will support 4.0.11, 0.5.0 will support 4.1 - should be coming next few days

Hello. Any news about 0.5.0 release?

**Comment by atmaniak** [comment]
Hi,
is there any way we can help you to have the 0.5.0 release ?

**Comment by cruse1977** [comment]
Doing final testing now - and looking to merge in some community PR's along the way - hopefully next few days
