### ISSUE TITLE
Plugin buttons not responding - take 2

### ISSUE THREAD

**Issue by xavbroadcast** [netbox-community/netbox-floorplan-plugin#44]
Having read https://github.com/netbox-community/netbox-floorplan-plugin/issues/27, I've been through it and this doesn't seem to fix my issue.
Ubuntu 22.04
Netbox 4.0.10
Python 3.10.12

I have debug set to true.
Plugin is installed.

As a sidenote, there's some confusion in the documentation. Sometimes, it's `netbox_floorplan`, sometimes it's `netbox_floorplan_plugin`. 

I've opted for the shorter version, but the documentation still suggests:
```
cd /opt/netbox
sudo ./venv/bin/python3 netbox/manage.py makemigrations netbox_floorplan_plugin
sudo ./venv/bin/python3 netbox/manage.py migrate
```
Running these commande (but using the `netbox_floorplan` value instead), I get:
```
(venv) root@netbox:/opt/netbox/netbox# python3 manage.py makemigrations
Migrations for 'core':
  core/migrations/0011_alter_datafile_hash.py
    - Alter field hash on datafile
(venv) root@netbox:/opt/netbox/netbox# python3 manage.py migrate
Operations to perform:
  Apply all migrations: account, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_floorplan, netbox_topology_views, sessions, social_django, taggit, tenancy, users, viualization, vpn, wireless
Running migrations:
  Applying core.0011_alter_datafile_hash... OK
```

I then do the 
```
(venv) root@netbox:/opt/netbox/netbox# python3 manage.py makemigrations netbox_floorplan
No changes detected in app 'netbox_floorplan'
(venv) root@netbox:/opt/netbox/netbox# python3 manage.py collectstatic --no-input

0 static files copied to '/opt/netbox-4.0.10/netbox/static', 549 unmodified.
```
So nothing is changed?

I can see all the files in the static/netbox_floorplan/ (in case it was an issue someone had commented on before) :
```
(venv) root@netbox:/opt/netbox/netbox/static/netbox_floorplan/floorplan# ls -al
total 44
drwxr-xr-x 2 root root  4096 Sep  4 15:38 .
drwxr-xr-x 4 root root  4096 Sep  4 15:19 ..
-rw-r--r-- 1 root root 20894 Sep  4 15:38 edit.js
-rw-r--r-- 1 root root  5611 Sep  4 15:38 utils.js
-rw-r--r-- 1 root root  1515 Sep  4 15:38 view.js
```

So as far as I can tell, it looks like it's all there,
But when I go to a location, I have the Floorplan tab, when I go to add a new floorplan, when I click on the Set Dimensions button, nothing happens. Opening up in the developer tab in Chrome, I get this error: `(index):2642 Uncaught ReferenceError: set_dimensions is not defined at HTMLAnchorElement.onclick ((index):2642:72)`

Any ideas?

**Comment by xavbroadcast** [comment]
> It then appears to reach out to https://unpkg.com/htmx.org@1.9.12 and fails to load a resource, again, as the host is offline and disconnected from the internet.
> 
> Is there a required dependency for htmx not otherwise installed with netbox, or if it is installed with netbox, how/where do I change the reference to point to an internal location?

You're right, I did notice this too and this install is also offline with no easy way to provide internet access. I can confirm by testing anothe online install I have and see if I have the same problem, but I guess it'll be ok.

If there's a dependency missing, I'm hoping it can be resolved separately so my NetBox can remain airgapped from the internet.

**Comment by cruse1977** [comment]
in 0.5.0 we'll move this to packaged with the plugin

**Comment by Idoheled** [comment]
When do you think 0.5.0 will be released?
This is so needed for my organization at the moment!
Thank you very much, much appreciated!
