### ISSUE TITLE
Background images not working

### ISSUE THREAD

**Issue by Azmodeszer** [netbox-community/netbox-floorplan-plugin#5]
Taken from https://github.com/tbotnz/netbox_floorplan/issues/26

There's three inquiries/issues here...

1. Uploading a background image for locations is giving me a Python error:

`'NoneType' object has no attribute 'id'`

2. Uploading a background image for sites is going through, but there is nothing displayed in the floorplan tab. It's the usual blank canvas. I checked the actual file system, the image is there and has the needed Linux permissions. Do images have to meet certain file type and/or size requirements? The documentation didn't say (or I missed it).

3. When adding (or updating) a floor plan through the Admin page, why is the Tags field required?

Thanks.

Python version: 3.11.2
NetBox version: 3.7.3
netbox_floorplan: 0.4

**Comment by DanSheps** [comment]
Okay, probably because I don't use floorplan right now, but how do you upload a floor plan?

LOL

**Comment by Azmodeszer** [comment]
Admin > Floorplans >Select floorplan to change >Background image

**Comment by DanSheps** [comment]
I didn't have any issue with that workflow using this fork.

**Comment by jeffgdotorg** [comment]
@Azmodeszer have you managed to reproduce this problem using a freshly installed system as your starting point? I want to drive us to a fix but it appears there's some inconsistency in different people's ability to see the problem in action.

**Comment by DanSheps** [comment]
> @Azmodeszer have you managed to reproduce this problem using a freshly installed system as your starting point? I want to drive us to a fix but it appears there's some inconsistency in different people's ability to see the problem in action.

Honestly, we should just move it to the new style admin panel.

**Comment by Azmodeszer** [comment]
> @Azmodeszer have you managed to reproduce this problem using a freshly installed system as your starting point? I want to drive us to a fix but it appears there's some inconsistency in different people's ability to see the problem in action.

I have not tried it on a completely fresh install (yet), no. When/if I get around to it, I will post my findings.

**Comment by cruse1977** [comment]
I now have the full history of this and whilst the admin panel was there, the javascript code for this was not due to scaling problems and a change in JS library. 

I have a version that semi works but with mass scaling issues alongside we'd need to move the upload over to django storage this is potentially a lot of work.
